#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollCenterWeb.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PYRCNT")]
	public partial class PRCDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PRCDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PYRCNTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PRCDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PRCDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PRCDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PRCDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DivisionStatus> DivisionStatus
		{
			get
			{
				return this.GetTable<DivisionStatus>();
			}
		}
		
		public System.Data.Linq.Table<DivisionStatusView> DivisionStatusViews
		{
			get
			{
				return this.GetTable<DivisionStatusView>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PauseDivision")]
		public int PauseDivision([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DivisionCode", DbType="VarChar(100)")] string divisionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PauseType", DbType="VarChar(50)")] string pauseType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PauseCode", DbType="Char(1)")] System.Nullable<char> pauseCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequesterID", DbType="VarChar(25)")] string requesterID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), divisionCode, pauseType, pauseCode, requesterID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubmitDivisionRequest")]
		public int SubmitDivisionRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DivisionCode", DbType="VarChar(50)")] string divisionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestCode", DbType="VarChar(50)")] string requestCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestText", DbType="VarChar(1000)")] string requestText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequesterID", DbType="VarChar(25)")] string requesterID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), divisionCode, requestCode, requestText, requesterID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubmitOverrideExtractBalanceRequest")]
		public int SubmitOverrideExtractBalanceRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DivisionCode", DbType="VarChar(50)")] string divisionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequesterID", DbType="VarChar(25)")] string requesterID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), divisionCode, requesterID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPittsburgStatus")]
		public ISingleResult<GetPittsburgStatusResult> GetPittsburgStatus()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetPittsburgStatusResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DivisionStatus")]
	public partial class DivisionStatus
	{
		
		private string _DivisionCode;
		
		private string _StatusCode;
		
		private string _ActionStatusCode;
		
		private string _ErrorStatusCode;
		
		private string _RequestCode;
		
		private string _RequestID;
		
		private string _StatusDetailText;
		
		private System.Nullable<char> _PauseDivision;
		
		private System.Nullable<char> _PauseExtract;
		
		private System.Nullable<char> _PauseImport;
		
		public DivisionStatus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DivisionCode
		{
			get
			{
				return this._DivisionCode;
			}
			set
			{
				if ((this._DivisionCode != value))
				{
					this._DivisionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StatusCode
		{
			get
			{
				return this._StatusCode;
			}
			set
			{
				if ((this._StatusCode != value))
				{
					this._StatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionStatusCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ActionStatusCode
		{
			get
			{
				return this._ActionStatusCode;
			}
			set
			{
				if ((this._ActionStatusCode != value))
				{
					this._ActionStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorStatusCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ErrorStatusCode
		{
			get
			{
				return this._ErrorStatusCode;
			}
			set
			{
				if ((this._ErrorStatusCode != value))
				{
					this._ErrorStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestCode", DbType="VarChar(50)")]
		public string RequestCode
		{
			get
			{
				return this._RequestCode;
			}
			set
			{
				if ((this._RequestCode != value))
				{
					this._RequestCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", DbType="VarChar(25)")]
		public string RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this._RequestID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusDetailText", DbType="VarChar(255)")]
		public string StatusDetailText
		{
			get
			{
				return this._StatusDetailText;
			}
			set
			{
				if ((this._StatusDetailText != value))
				{
					this._StatusDetailText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PauseDivision", DbType="Char(1)")]
		public System.Nullable<char> PauseDivision
		{
			get
			{
				return this._PauseDivision;
			}
			set
			{
				if ((this._PauseDivision != value))
				{
					this._PauseDivision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PauseExtract", DbType="Char(1)")]
		public System.Nullable<char> PauseExtract
		{
			get
			{
				return this._PauseExtract;
			}
			set
			{
				if ((this._PauseExtract != value))
				{
					this._PauseExtract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PauseImport", DbType="Char(1)")]
		public System.Nullable<char> PauseImport
		{
			get
			{
				return this._PauseImport;
			}
			set
			{
				if ((this._PauseImport != value))
				{
					this._PauseImport = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DivisionStatusView")]
	public partial class DivisionStatusView
	{
		
		private string _DivisionCode;
		
		private string _DivisionName;
		
		private string _DivisionStatus;
		
		private string _DivisionStatusColor;
		
		private string _ActionStatus;
		
		private string _ActionStatusColor;
		
		private string _ErrorStatus;
		
		private string _ErrorStatusColor;
		
		private System.Nullable<char> _PauseDivision;
		
		private System.Nullable<char> _PauseExtract;
		
		private System.Nullable<char> _PauseImport;
		
		private string _RequestCode;
		
		private string _RequestID;
		
		private string _StatusDetailText;
		
		public DivisionStatusView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DivisionCode
		{
			get
			{
				return this._DivisionCode;
			}
			set
			{
				if ((this._DivisionCode != value))
				{
					this._DivisionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DivisionName
		{
			get
			{
				return this._DivisionName;
			}
			set
			{
				if ((this._DivisionName != value))
				{
					this._DivisionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionStatus", DbType="VarChar(255)")]
		public string DivisionStatus
		{
			get
			{
				return this._DivisionStatus;
			}
			set
			{
				if ((this._DivisionStatus != value))
				{
					this._DivisionStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionStatusColor", DbType="VarChar(8)")]
		public string DivisionStatusColor
		{
			get
			{
				return this._DivisionStatusColor;
			}
			set
			{
				if ((this._DivisionStatusColor != value))
				{
					this._DivisionStatusColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionStatus", DbType="VarChar(255)")]
		public string ActionStatus
		{
			get
			{
				return this._ActionStatus;
			}
			set
			{
				if ((this._ActionStatus != value))
				{
					this._ActionStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionStatusColor", DbType="VarChar(8)")]
		public string ActionStatusColor
		{
			get
			{
				return this._ActionStatusColor;
			}
			set
			{
				if ((this._ActionStatusColor != value))
				{
					this._ActionStatusColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorStatus", DbType="VarChar(255)")]
		public string ErrorStatus
		{
			get
			{
				return this._ErrorStatus;
			}
			set
			{
				if ((this._ErrorStatus != value))
				{
					this._ErrorStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorStatusColor", DbType="VarChar(8)")]
		public string ErrorStatusColor
		{
			get
			{
				return this._ErrorStatusColor;
			}
			set
			{
				if ((this._ErrorStatusColor != value))
				{
					this._ErrorStatusColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PauseDivision", DbType="Char(1)")]
		public System.Nullable<char> PauseDivision
		{
			get
			{
				return this._PauseDivision;
			}
			set
			{
				if ((this._PauseDivision != value))
				{
					this._PauseDivision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PauseExtract", DbType="Char(1)")]
		public System.Nullable<char> PauseExtract
		{
			get
			{
				return this._PauseExtract;
			}
			set
			{
				if ((this._PauseExtract != value))
				{
					this._PauseExtract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PauseImport", DbType="Char(1)")]
		public System.Nullable<char> PauseImport
		{
			get
			{
				return this._PauseImport;
			}
			set
			{
				if ((this._PauseImport != value))
				{
					this._PauseImport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestCode", DbType="VarChar(50)")]
		public string RequestCode
		{
			get
			{
				return this._RequestCode;
			}
			set
			{
				if ((this._RequestCode != value))
				{
					this._RequestCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", DbType="VarChar(25)")]
		public string RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this._RequestID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusDetailText", DbType="VarChar(255)")]
		public string StatusDetailText
		{
			get
			{
				return this._StatusDetailText;
			}
			set
			{
				if ((this._StatusDetailText != value))
				{
					this._StatusDetailText = value;
				}
			}
		}
	}
	
	public partial class GetPittsburgStatusResult
	{
		
		private string _ERIStatus;
		
		private string _JOHStatus;
		
		private string _PITStatus;
		
		public GetPittsburgStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERIStatus", DbType="VarChar(10)")]
		public string ERIStatus
		{
			get
			{
				return this._ERIStatus;
			}
			set
			{
				if ((this._ERIStatus != value))
				{
					this._ERIStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOHStatus", DbType="VarChar(10)")]
		public string JOHStatus
		{
			get
			{
				return this._JOHStatus;
			}
			set
			{
				if ((this._JOHStatus != value))
				{
					this._JOHStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PITStatus", DbType="VarChar(10)")]
		public string PITStatus
		{
			get
			{
				return this._PITStatus;
			}
			set
			{
				if ((this._PITStatus != value))
				{
					this._PITStatus = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
